loopring:
  link-collector:
    initial-delay-str: 5000
    fixed-rate-str: 600000

  link-processors:
    initial-delay-str: 5000
    fixed-rate-str: 900000

  entity-processors:
    initial-delay-str: 8000
    fixed-rate-str: 300000

  processor-threadpool-max: 6

  execute-only-once-collectors:
    - task-name: cmc-coin-infos
      source-site-name: cmc
      selector-key: cmc-coin-data-selector
      target-entity: "org.loopring.crawler.models.Coin"
      crawl-method: json
      crawl-type: multiple
      link-generator-config:
        link-url-template: "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing?start=${0}&limit=100"
        params-config:
          - param-type-str: numberSeq
            start: 1
            end: 1000
            step: 100

  all-selectors:
    - key: cmc-coin-data-selector
      source-site-name: cmc
      is-root: true
      name: root
      json-path: "$.data.cryptoCurrencyList"
      children:
        - name: "name"
          json-path: "$.name"
        - name: "symbol"
          json-path: "$.symbol"
        - name: "uuidFields"
          value-type: "constant"
          const-value: "name"

  entity-tasks:
    - cmc-coin-infos
